#!/bin/bash
#set -x
EXEC="${1}"; shift
if [ -z "${EXEC}" ]; then
    EXEC="/usr/share/max/bin/max"
fi

if [ -z "${EXEC}" ]; then
    echo "Usage: AppImage <exec file>"
    exit 1
fi

#LANG="ru_RU.UTF-8"

CNT_ARGS_FILE="/tmp/args"
trap "rm -f $CNT_ARGS_FILE" EXIT

CNT_SETUP=( bwrap
--unshare-user
--uid 0
--gid 0
--unshare-pid
--unshare-ipc
#--unshare-cgroup
#--unshare-net
#--overlay-src ${APPIMAGE_BASE}
#--overlay-src ${APPDIR}
#--tmp-overlay /
--bind ${APPDIR} /
--bind /dev/null /AppRun
#--bind /dev/null /max.desktop
#--bind /dev/null /max.png
--proc /proc
--dev-bind /dev /dev
#--dev /dev
--bind /sys /sys
#--bind /run /run
--tmpfs /run
--bind /run/dbus /run/dbus
--bind /run/user /run/user
--bind /run/lock /run/lock
--bind /run/udev /run/udev
--bind /run/polkit /run/polkit
#--bind /home /home
--bind ${HOME} /root
#--bind /tmp /tmp
--tmpfs /tmp
--dir /tmp/.X11-unix
--bind /tmp/.X11-unix /tmp/.X11-unix
--clearenv
--setenv DISPLAY ${DISPLAY}
--setenv LANG ${LANG}
--setenv HOME /root
--setenv DBUS_SESSION_BUS_ADDRESS ${DBUS_SESSION_BUS_ADDRESS}
--setenv PULSE_SERVER ${XDG_RUNTIME_DIR}/pulse/native
)

CNT_SETUP_STR="${CNT_SETUP[@]} "
CNT_SETUP_STR="${CNT_SETUP_STR#bwrap }"
echo -n "$CNT_SETUP_STR" | tr ' ' '\0' > "$CNT_ARGS_FILE"
#echo "--dev-bind / / " | tr ' ' '\0' > "$CNT_ARGS_FILE"

function unlock_keyring ()
{
    read -rsp "Keyring password: " pass
    echo -n "$pass" | gnome-keyring-daemon --daemonize --replace --unlock
    unset pass
}

# Might be useful in the future
function lock_keyring ()
{
    pkill -u "$(whoami)" -f gnome-keyring-daemon
}

echo "Executing ${EXEC}"
echo "${HOME} will be mapped to /root"
#echo "DISPLAY=${DISPLAY}"
echo "LANG=${LANG}"
if [ "${HOME}" != "/home/maxuser" ]; then
    echo "Wrong user detected, exiting. Next time, try:"
    echo "ssh -X maxuser@localhost"
    exit 1
fi
while true; do
    read -p "Is it OK? [y/n] " reply
    if [ "${reply}" == "y" ]; then
       unlock_keyring
#      exec "${CNT_SETUP[@]}" "${EXEC}" "$@"
        exec {args_fd}< "$CNT_ARGS_FILE" && rm -f "$CNT_ARGS_FILE"
        if [ "${EXEC}" == "/usr/share/max/bin/max" ]; then
            exec -a /sbin/init bwrap --args ${args_fd} "${EXEC}" </dev/null >/dev/null 2>&1
        else
            exec -a /sbin/init bwrap --args ${args_fd} "${EXEC}" "$@"
        fi
    elif [ "${reply}" == "n" ]; then
        echo "Exiting..."
        exit 0
    else
        echo "Please answer y/n"
    fi
done

