#!/bin/bash
#set -x
EXEC="${1}"; shift
if [ -z "${EXEC}" ]; then
    EXEC="/opt/google/earth/pro/google-earth-pro"
fi

if [ -z "${EXEC}" ]; then
    echo "Usage: AppImage <exec file>"
    exit 1
fi

#LANG="ru_RU.UTF-8"

CNT_ARGS_FILE="/tmp/args"
trap "rm -f $CNT_ARGS_FILE" EXIT

CNT_SETUP=( bwrap
--unshare-user
--uid 0
--gid 0
#--unshare-pid
#--unshare-ipc
#--unshare-cgroup
#--unshare-net
#--overlay-src ${APPIMAGE_BASE}
#--overlay-src ${APPDIR}
#--tmp-overlay /
--bind ${APPDIR} /
--bind /dev/null /AppRun
#--bind /dev/null /max.desktop
#--bind /dev/null /max.png
--proc /proc
--dev-bind /dev /dev
#--dev /dev
--bind /sys /sys
--bind /run /run
#--bind /home /home
--bind ${HOME} /root
#--bind /tmp /tmp
--tmpfs /tmp
--dir /tmp/.X11-unix
--bind /tmp/.X11-unix /tmp/.X11-unix
--clearenv
--setenv DISPLAY ${DISPLAY}
--setenv LANG ${LANG}
--setenv HOME /root
)

CNT_SETUP_STR="${CNT_SETUP[@]} "
CNT_SETUP_STR="${CNT_SETUP_STR#bwrap }"
echo -n "$CNT_SETUP_STR" | tr ' ' '\0' > "$CNT_ARGS_FILE"
#echo "--dev-bind / / " | tr ' ' '\0' > "$CNT_ARGS_FILE"


echo "Executing ${EXEC}"
echo "${HOME} will be mapped to /root"
#echo "DISPLAY=${DISPLAY}"
echo "LANG=${LANG}"
while true; do
    read -p "Is it OK? [y/n] " reply
    if [ "${reply}" == "y" ]; then
#      exec "${CNT_SETUP[@]}" "${EXEC}" "$@"
        exec {args_fd}< "$CNT_ARGS_FILE" && rm -f "$CNT_ARGS_FILE"
        exec -a /sbin/init bwrap --args ${args_fd} "${EXEC}" "$@"
    elif [ "${reply}" == "n" ]; then
        echo "Exiting..."
        exit 0
    else
        echo "Please answer y/n"
    fi
done

