#!/bin/bash
#set -x
EXEC="${1}"; shift
LANG=en_US.UTF-8
#EXEC="/usr/share/max/bin/max"
if [ -z "${EXEC}" ]; then
    EXEC="/usr/lib/systemd/systemd"
#    set -- "--log-target=console" "--log-level=warning"
    set -- "--log-target=journal" "--log-level=debug"
#    set -- "--log-target=console" "--log-level=debug"
fi

if [ -z "${EXEC}" ]; then
    echo "Usage: AppImage <exec file>"
    exit 1
fi
#if [ -z "${APPIMAGE_BASE}" ]; then
#    echo "APPIMAGE_BASE not set"
#    exit 1
#fi
#[ -z "${PWD}" ] && PWD=$(pwd)
#HOME_DIR=$(realpath ${PWD})
HOME_DIR="/home/subs/maxhome1"
CNT_HOME_DIR="/home/maxuser"

#ulimit -c unlimited
[ ! -d /tmp/core ] && mkdir /tmp/core

CNT_ARGS_FILE="/tmp/args"
trap "rm -f $CNT_ARGS_FILE" EXIT

# From https://github.com/containers/bubblewrap/issues/468
# Thank you, guys
set -euo pipefail

info_pipe=$(mktemp -u) || exit $?
userns_pipe=$(mktemp -u) || exit $?

mkfifo "${info_pipe}" || exit $?
mkfifo "${userns_pipe}" || exit $?

(
# jq is the hard dependency for launching these AppImages with user mapping
    pid=$(<"${info_pipe}" /usr/bin/jq '."child-pid"')
    [ -z "$pid" ] && exit 0

    newuidmap "${pid}" 0 1000 1 1 100000 65536
    newgidmap "${pid}" 0 1000 1 1 100000 65536

    echo 1 > "${userns_pipe}"

    rm "${info_pipe}" "${userns_pipe}"
) &

exec {info_fd}<>"${info_pipe}"
exec {userns_fd}<>"${userns_pipe}"

CNT_SETUP=( bwrap
--new-session
--as-pid-1
--info-fd "${info_fd}"
--userns-block-fd "${userns_fd}"
--unshare-user
--uid 0
--gid 0
--unshare-pid
--unshare-ipc
--unshare-uts
--unshare-cgroup
#--unshare-net
--overlay-src ${APPDIR}
--tmp-overlay /
--cap-add CAP_SETUID
--cap-add CAP_SETGID
--cap-add CAP_MKNOD
--cap-add CAP_SYS_ADMIN
--cap-add CAP_SETPCAP
--cap-add CAP_CHOWN
--cap-add CAP_FOWNER
--cap-add CAP_SYS_TTY_CONFIG
--cap-add CAP_SYS_RAWIO
--cap-add CAP_SYS_RESOURCE
--cap-add CAP_SYS_CHROOT
--cap-add CAP_NET_ADMIN
--cap-add CAP_DAC_OVERRIDE
--cap-add CAP_SETFCAP
--cap-add CAP_KILL
#--cap-add ALL
#--bind ${APPDIR} /
--proc /proc
--ro-bind /proc/sys /proc/sys
#--dev-bind /dev /dev
#--dev /dev
--tmpfs /dev
--dev-bind /dev/null /dev/null
--dev-bind /dev/zero /dev/zero
--dev-bind /dev/full /dev/full
--dev-bind /dev/random /dev/random
--dev-bind /dev/urandom /dev/urandom
--dev-bind /dev/tty /dev/tty
--dir /dev/pts
--chmod 755 /dev/pts
--ro-bind /sys /sys
--tmpfs /run
--tmpfs /run/lock
--dir /run/systemd
--dir /run/varlink/registry
--dir /run/user
--perms 1777
--tmpfs /tmp
--bind /tmp/.X11-unix /tmp/.X11-unix
--bind /tmp/core /tmp/core
#--bind /tmp/.ICE-unix /tmp/.ICE-unix
--bind ${HOME_DIR} ${CNT_HOME_DIR}
--tmpfs /var/tmp
--ro-bind ${APPDIR}/init.sh /init.sh
--clearenv
--setenv container bwrap-appimage
#--setenv container_ttys pts/1
--setenv DISPLAY ${DISPLAY}
--setenv LANG ${LANG}
--setenv HOME ${CNT_HOME_DIR}
)

CNT_SETUP_STR="${CNT_SETUP[@]} "
CNT_SETUP_STR="${CNT_SETUP_STR#bwrap }"
echo -n "$CNT_SETUP_STR" | tr ' ' '\0' > "$CNT_ARGS_FILE"
#echo "--dev-bind / / " | tr ' ' '\0' > "$CNT_ARGS_FILE"

busctl call org.freedesktop.machine1 \
            /org/freedesktop/machine1 \
            org.freedesktop.machine1.Manager \
            CreateMachine \
            "sayssusa(sv)" \
            "aicontainer" \
            0 \
            "" \
            "container" \
            $$ \
            "" \
            0 || exit 1

mkdir /sys/fs/cgroup/machine.slice/machine-aicontainer.scope/leaf &&\
echo $$ > /sys/fs/cgroup/machine.slice/machine-aicontainer.scope/leaf/cgroup.procs

echo "Contents of /proc/$$/cgroup:"
cat /proc/$$/cgroup
echo "Executing ${EXEC}"
echo "${HOME_DIR} will be mapped to ${CNT_HOME_DIR}"
#echo "DISPLAY=${DISPLAY}"
echo "LANG=${LANG}"
while true; do
    read -p "Is it OK? [y/n] " reply
    if [ "${reply}" == "y" ]; then
#      exec "${CNT_SETUP[@]}" "${EXEC}" "$@"
        exec {args_fd}< "$CNT_ARGS_FILE" && rm -f "$CNT_ARGS_FILE"
#        exec -a /sbin/init bwrap --args ${args_fd} "${EXEC}" "$@"
        exec -a /sbin/init bwrap --args ${args_fd} -- /init.sh "${EXEC}" "$@"
#        exec -a /sbin/init bwrap --args ${args_fd} setpriv --reuid=1001 --regid=1001 --inh-caps=-all --ambient-caps=-all --clear-groups "${EXEC}" "$@"
    elif [ "${reply}" == "n" ]; then
        echo "Exiting..."
        exit 0
    else
        echo "Please answer y/n"
    fi
done

